dbt_project:
  target: local
  outputs:
    local:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      database: DEV_SANDY
      schema: PUBLIC
      warehouse: ELEMENTL
      client_session_keep_alive: False

